# -*- coding: utf-8 -*-
"""TO_EXECUTE_AS_Linkedin_v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BH2ToaL_-cTksGILuxo7aqY3FG706B2P
"""

import pandas as pd
import requests
import time
import re
import os
import argparse
from datetime import datetime, timezone
from html import unescape

import brave_quota_manager

# ── Credentials ───────────────────────────────────────────────────────────────
BRAVE_API_KEY = brave_quota_manager.get_brave_api_key()

# ── Added Argument Parsing ──
def get_args():
    parser = argparse.ArgumentParser(description='LinkedIn post scraper with dynamic seed selection.')
    parser.add_argument('--seeds', type=str, help='Name of the seeds file in clean_seeds/ (e.g., seeds_buyside_london.csv)')
    return parser.parse_args()

args = get_args()
SEEDS_DIR = 'clean_seeds'

if args.seeds:
    INPUT_CSV = os.path.join(SEEDS_DIR, args.seeds)
    if not os.path.exists(INPUT_CSV):
        print(f"Error: {INPUT_CSV} not found.")
        exit(1)
    seed_base = os.path.splitext(args.seeds)[0]
    name_part = seed_base.replace('seeds_', '')
    timestamp = datetime.now().strftime("%y-%m-%d-%H")
    OUTPUT_CSV = f"linkedin_{name_part}_{timestamp}.csv"
else:
    INPUT_CSV     = "clean_seeds/seeds_buyside_eu_uae.csv"
    OUTPUT_CSV    = "news_buyside_eu_uae_linkedin_fallback.csv"

brave_quota_manager.start_run(INPUT_CSV)

DELAY_SECONDS = 1.2
MAX_RESULTS   = 5


# ══════════════════════════════════════════════════════════════════════════════
# DATE EXTRACTION — THREE STRATEGIES, CHOSEN BY URL TYPE
#
#  URL type                 │ Strategy
#  ─────────────────────────┼──────────────────────────────────────────────────
#  /posts/…activity-ID…     │ A — Snowflake decode  (instant, exact timestamp)
#  /in/{slug}  (profile)    │ B — Slug-targeted search: site:linkedin.com/posts/{slug}
#  /company/{slug}          │ B — same slug-targeted search
#  other / no LinkedIn      │ C — Snippet regex fallback (relative / ISO pattern)
#
#  Strategy B re-uses the PROFILE SLUG already present in the retrieved URL.
#  LinkedIn post URLs are structured as:
#    /posts/{author-slug}_{title}-activity-{id}-{suffix}
#  So  site:linkedin.com/posts/{slug}  fetches only posts authored by that
#  person or company — the first result will have an activity ID to decode.
# ══════════════════════════════════════════════════════════════════════════════


# ── Snowflake helpers ─────────────────────────────────────────────────────────

_ACTIVITY_RE = re.compile(r"activity-(\d{15,20})")

def _snowflake_decode(activity_id: int) -> datetime:
    ms = activity_id >> 22
    return datetime.fromtimestamp(ms / 1000.0, tz=timezone.utc)

def _relative_age(dt: datetime) -> str:
    now   = datetime.now(tz=timezone.utc)
    delta = now - dt
    days  = delta.days
    if days < 0:   return "future?"
    if days == 0:
        h = delta.seconds // 3600
        return f"{h} hour{'s' if h != 1 else ''} ago" if h else "just now"
    if days == 1:  return "1 day ago"
    if days < 7:   return f"{days} days ago"
    w = days // 7
    if w < 5:      return f"{w} week{'s' if w > 1 else ''} ago"
    m = days // 30
    if m < 12:     return f"{m} month{'s' if m > 1 else ''} ago"
    y = days // 365
    rm = (days % 365) // 30
    suffix = f" {rm} month{'s' if rm > 1 else ''} ago" if rm else " ago"
    return f"{y} year{'s' if y > 1 else ''}{suffix}"

def _iso_to_relative(iso: str) -> str:
    try:
        clean = re.sub(r"[TZ].*", "", iso).replace("/", "-")
        parts = clean.split("-")
        dt = datetime(int(parts[0]), int(parts[1]), int(parts[2] if len(parts) > 2 else 1),
                      tzinfo=timezone.utc)
        return _relative_age(dt)
    except Exception:
        return ""

def _find_iso(text: str) -> str:
    m = re.search(r"(20\d{2}[-/]\d{2}[-/]\d{2}(?:T[\d:+Z.\-]+)?)", text)
    return m.group(1) if m else ""

def _find_relative(text: str) -> str:
    m = re.search(r"\b(\d+)\s+(second|minute|hour|day|week|month|year)s?\s+ago\b",
                  text, re.IGNORECASE)
    return m.group(0) if m else ""


# ── URL classifier ────────────────────────────────────────────────────────────

def classify_url(url: str) -> str:
    """Return one of: 'post' | 'profile' | 'company' | 'other'"""
    if _ACTIVITY_RE.search(url):            return "post"
    if re.search(r"linkedin\.com/in/",      url): return "profile"
    if re.search(r"linkedin\.com/company/", url): return "company"
    return "other"

def extract_slug(url: str) -> str:
    """Extract the /in/{slug} or /company/{slug} identifier."""
    m = re.search(r"linkedin\.com/(?:in|company)/([^/?#]+)", url)
    return m.group(1) if m else ""


# ── Brave Search ──────────────────────────────────────────────────────────────

def google_search(query: str, num: int = MAX_RESULTS) -> list:
    can_call, reason = brave_quota_manager.can_make_call(INPUT_CSV)
    if not can_call:
        print(f"    ⚠ Quota limit reached ({reason}) — skipping search")
        return []

    url = "https://api.search.brave.com/res/v1/web/search"
    headers = {
        "Accept": "application/json",
        "Accept-Encoding": "gzip",
        "X-Subscription-Token": BRAVE_API_KEY
    }
    params = {"q": query, "count": num}
    try:
        resp = requests.get(url, headers=headers, params=params, timeout=15)
        resp.raise_for_status()
        brave_quota_manager.record_call(INPUT_CSV, 1)
        data = resp.json()
        results = data.get("web", {}).get("results", [])
        items = []
        for r in results:
            items.append({
                "link": r.get("url", ""),
                "title": r.get("title", ""),
                "snippet": r.get("description", ""),
                "htmlSnippet": r.get("description", ""),
                "pagemap": {}
            })
        return items
    except Exception as e:
        print(f"    ⚠  Brave search error — {e}")
        return []


# ── Strategy A: Snowflake decode from activity ID ─────────────────────────────

def strategy_a(url: str) -> dict | None:
    """Decode timestamp directly from the activity ID embedded in the URL."""
    m = _ACTIVITY_RE.search(url)
    if not m:
        return None
    try:
        dt  = _snowflake_decode(int(m.group(1)))
        iso = dt.strftime("%Y-%m-%dT%H:%M:%SZ")
        return {"post_date": iso, "relative_age": _relative_age(dt),
                "date_source": "A:snowflake", "post_url": url}
    except Exception:
        return None


# ── Strategy B: Slug-targeted post search ────────────────────────────────────

def strategy_b(url: str) -> dict | None:
    """
    For profile or company URLs, extract the slug and query:
        site:linkedin.com/posts/{slug}
    LinkedIn post URLs embed the author's slug as a prefix:
        /posts/{author-slug}_{title}-activity-{id}-{suffix}
    The first Google result will be the most recent post by that author.
    """
    slug = extract_slug(url)
    if not slug:
        return None

    query = f"site:linkedin.com/posts/{slug}"
    items = google_search(query, num=MAX_RESULTS)
    time.sleep(DELAY_SECONDS)

    for item in items:
        post_url = item.get("link", "")
        result = strategy_a(post_url)   # decode the activity ID in the found post
        if result:
            result["date_source"] = f"B:slug({slug})"
            result["post_url"]    = post_url
            return result

    return None


# ── Strategy C: Snippet / metadata regex fallback ────────────────────────────

_META_DATE_KEYS = [
    "article:published_time", "article:modified_time", "og:updated_time",
    "publish_date", "pubdate", "date", "dc.date",
]
_ENTITY_TYPES = ["newsarticle", "article", "blogposting", "socialmediaposting"]

def strategy_c(item: dict) -> dict | None:
    """Last resort: extract date from Google's pagemap / snippet text."""
    pagemap = item.get("pagemap", {})

    for mt in pagemap.get("metatags", []):
        for key in _META_DATE_KEYS:
            val = mt.get(key, "").strip()
            if val:
                iso = _find_iso(val) or val[:25]
                return {"post_date": iso, "relative_age": _iso_to_relative(iso),
                        "date_source": f"C:metatag({key})", "post_url": item.get("link", "")}

    for etype in _ENTITY_TYPES:
        for entity in pagemap.get(etype, []):
            val = entity.get("datepublished", "").strip()
            if val:
                iso = _find_iso(val) or val[:25]
                return {"post_date": iso, "relative_age": _iso_to_relative(iso),
                        "date_source": f"C:pagemap({etype})", "post_url": item.get("link", "")}

    for label, raw in (("htmlSnippet", item.get("htmlSnippet", "")),
                       ("snippet",     item.get("snippet",     ""))):
        text = unescape(raw)
        rel  = _find_relative(text)
        if rel:
            return {"post_date": _find_iso(text), "relative_age": rel,
                    "date_source": f"C:{label}(relative)", "post_url": item.get("link", "")}
        iso = _find_iso(text)
        if iso:
            return {"post_date": iso, "relative_age": _iso_to_relative(iso),
                    "date_source": f"C:{label}(iso)", "post_url": item.get("link", "")}

    return None


# ── Text helpers ──────────────────────────────────────────────────────────────

def best_text(item: dict) -> str:
    og = item.get("pagemap", {}).get("metatags", [{}])[0].get("og:description", "").strip()
    if og: return og
    hs = unescape(item.get("htmlSnippet", "")).strip()
    if hs: return hs
    return item.get("snippet", "").strip()

def clean_text(text: str) -> str:
    text = re.sub(r"^\d+\s+(?:second|minute|hour|day|week|month|year)s?\s+ago\s*[·\-–—]?\s*",
                  "", text, flags=re.IGNORECASE)
    return re.sub(r"\s+", " ", text).strip()


# ── Core processor ────────────────────────────────────────────────────────────

def process_seed(seed: str) -> dict:
    query = f"{seed} linkedin"
    items = google_search(query, num=MAX_RESULTS)
    time.sleep(DELAY_SECONDS)

    # Pick the best item: prefer any that already has an activity ID
    chosen = next((it for it in items if _ACTIVITY_RE.search(it.get("link", ""))), None)
    if chosen is None:
        chosen = next((it for it in items if "linkedin.com" in it.get("link", "")), None)
    if chosen is None:
        chosen = items[0] if items else None

    paragraph = clean_text(best_text(chosen)) if chosen else "(no result)"
    result_url = chosen.get("link", "") if chosen else ""

    # ── Apply per-URL strategy ────────────────────────────────────────────────
    date_result = None
    url_type    = classify_url(result_url)

    if url_type == "post":
        # Strategy A: instant snowflake decode — no extra API call
        date_result = strategy_a(result_url)

    elif url_type in ("profile", "company"):
        # Strategy B: slug-targeted post search — 1 extra API call
        date_result = strategy_b(result_url)
        if date_result is None:
            # Strategy B found no post → try C on the original item metadata
            date_result = strategy_c(chosen) if chosen else None

    else:
        # Strategy C: snippet/metadata regex
        date_result = strategy_c(chosen) if chosen else None

    if date_result is None:
        date_result = {"post_date": "", "relative_age": "", "date_source": "not_found",
                       "post_url": result_url}

    return {
        "seed":            seed,
        "query":           query,
        "result_url":      result_url,
        "result_title":    chosen.get("title", "") if chosen else "",
        "url_type":        url_type,
        "post_url":        date_result["post_url"],
        "post_date":       date_result["post_date"],
        "relative_age":    date_result["relative_age"],
        "date_source":     date_result["date_source"],
        "first_paragraph": paragraph,
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if not os.path.exists(INPUT_CSV):
        raise FileNotFoundError(f"Not found: {INPUT_CSV}")

    df_in = pd.read_csv(INPUT_CSV, sep=",")
    df_in.columns = df_in.columns.str.strip()
    seeds_col = next((c for c in df_in.columns if c.lower() == "seeds"), None)
    if seeds_col is None:
        raise ValueError(f"No 'Seeds' column. Found: {list(df_in.columns)}")

    seeds = df_in[seeds_col].dropna().unique().tolist()
    print(f"✓ {len(seeds)} unique seeds  |  output → {OUTPUT_CSV}")
    print(f"  Max API calls: ~{len(seeds) * 2} (strategy B seeds use 2 calls each)\n")

    results = []
    t0 = time.time()

    for i, seed in enumerate(seeds, 1):
        print(f"[{i:>3}/{len(seeds)}] {seed[:72]}")
        row = process_seed(seed)
        results.append(row)

        age = row["relative_age"] or row["post_date"] or "—"
        print(f"         ↳ [{row['url_type']:<8}] [{row['date_source']:<30}]  {age}")
        print(f"           {row['first_paragraph'][:95]}")

        if i < len(seeds):
            time.sleep(DELAY_SECONDS)

    df_out = pd.DataFrame(results, columns=[
        "seed", "query", "result_url", "result_title", "url_type",
        "post_url", "post_date", "relative_age", "date_source", "first_paragraph",
    ])
    # Remove duplicate rows based on 'result_url' before exporting
    df_out.drop_duplicates(subset=['result_url'], inplace=True)

    df_out.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")

    elapsed = int(time.time() - t0)
    total   = len(results)
    captured= (df_out["relative_age"].str.len() > 0).sum()
    sa      = (df_out["date_source"].str.startswith("A:")).sum()
    sb      = (df_out["date_source"].str.startswith("B:")).sum()
    sc      = (df_out["date_source"].str.startswith("C:")).sum()
    miss    = (df_out["date_source"] == "not_found").sum()

    print(f"\n✅  {total} rows → '{OUTPUT_CSV}'  ({elapsed}s)")
    print(f"   Age captured : {captured}/{total}")
    print(f"   Strategy A   : {sa:>3}  (snowflake from post URL)")
    print(f"   Strategy B   : {sb:>3}  (slug-targeted search → snowflake)")
    print(f"   Strategy C   : {sc:>3}  (snippet / metadata regex)")
    print(f"   Not found    : {miss:>3}")

    brave_quota_manager.print_recap(INPUT_CSV)


if __name__ == "__main__":
    main()